apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: cv-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-app
  template:
    metadata:
      labels:
        app: cv-app
    spec:
      containers:
      - name: cv-app
        image: na6an/cv-app:latest #hub.docker.com/repository/docker/
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: cv-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: na6an/cv-app:latest 
    command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
  imagePullSecrets:
  - name: regcred